In [98]:
import pandas as pd
import numpy as np

In [99]:
df = pd.read_csv("iris.data.csv")

In [100]:
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

from matplotlib import pyplot as plt
_df_0['5.1'].plot(kind='hist', bins=20, title='5.1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['3.5'].plot(kind='hist', bins=20, title='3.5')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['1.4'].plot(kind='hist', bins=20, title='1.4')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['0.2'].plot(kind='hist', bins=20, title='0.2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='5.1', y='3.5', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='3.5', y='1.4', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='1.4', y='0.2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['0.2']
  ys = series['5.1']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('0.2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('0.2')
_ = plt.ylabel('5.1')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['0.2']
  ys = series['3.5']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('0.2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('0.2')
_ = plt.ylabel('3.5')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['0.2']
  ys = series['1.4']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('0.2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('0.2')
_ = plt.ylabel('1.4')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['0.2']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': '0.2'}, axis=1)
              .sort_values('0.2', ascending=True))
  xs = counted['0.2']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('0.2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('0.2')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_11['5.1'].plot(kind='line', figsize=(8, 4), title='5.1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['3.5'].plot(kind='line', figsize=(8, 4), title='3.5')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['1.4'].plot(kind='line', figsize=(8, 4), title='1.4')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['0.2'].plot(kind='line', figsize=(8, 4), title='0.2')
plt.gca().spines[['top', 'right']].set_visible(False)

In [101]:
# checking for null values
# seperate x and y
print(df.isna().sum())
x = df.drop("Iris-setosa", axis=1)
y = df["Iris-setosa"]

x.head()

5.1            0
3.5            0
1.4            0
0.2            0
Iris-setosa    0
dtype: int64


5.1  3.5  1.4  0.2
0  4.9  3.0  1.4  0.2
1  4.7  3.2  1.3  0.2
2  4.6  3.1  1.5  0.2
3  5.0  3.6  1.4  0.2
4  5.4  3.9  1.7  0.4

In [102]:
# class 0 ----> [1, 0, 0]
# class 1 ----> [0, 1, 0]
# class 2 ----> [0, 0, 1]

In [103]:
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

In [104]:
y.shape

(149,)

In [105]:
le = LabelEncoder()
y = le.fit_transform(y)

In [106]:
print("transformed_shape", y.shape)
print(y[:10])

transformed_shape (149,)
[0 0 0 0 0 0 0 0 0 0]


In [107]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
y_train = to_categorical(y_train)
x_train.head()

5.1  3.5  1.4  0.2
22  5.1  3.3  1.7  0.5
15  5.4  3.9  1.3  0.4
65  5.6  3.0  4.5  1.5
11  4.8  3.0  1.4  0.1
42  5.0  3.5  1.6  0.6

In [108]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [109]:
from keras.models import Sequential
from keras.layers import Dense

In [110]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [111]:
model.compile(loss = 'categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

In [112]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_23 (Dense)                     │ (None, 8)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_24 (Dense)                     │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_25 (Dense)                     │ (None, 3)                   │              27 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 139 (556.00 B)

 Trainable params: 139 (556.00 B)

 Non-trainable params: 0 (0.00 B)

In [113]:
model.fit(x_train, y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 1s - 259ms/step - accuracy: 0.3277 - loss: 1.3613
Epoch 2/150
4/4 - 0s - 7ms/step - accuracy: 0.3277 - loss: 1.3399
Epoch 3/150
4/4 - 0s - 15ms/step - accuracy: 0.3277 - loss: 1.3221
Epoch 4/150
4/4 - 0s - 7ms/step - accuracy: 0.3277 - loss: 1.3041
Epoch 5/150
4/4 - 0s - 14ms/step - accuracy: 0.3193 - loss: 1.2878
Epoch 6/150
4/4 - 0s - 7ms/step - accuracy: 0.3193 - loss: 1.2725
Epoch 7/150
4/4 - 0s - 7ms/step - accuracy: 0.3193 - loss: 1.2591
Epoch 8/150
4/4 - 0s - 7ms/step - accuracy: 0.3109 - loss: 1.2453
Epoch 9/150
4/4 - 0s - 14ms/step - accuracy: 0.3109 - loss: 1.2324
Epoch 10/150
4/4 - 0s - 9ms/step - accuracy: 0.3193 - loss: 1.2214
Epoch 11/150
4/4 - 0s - 7ms/step - accuracy: 0.3361 - loss: 1.2109
Epoch 12/150
4/4 - 0s - 14ms/step - accuracy: 0.3782 - loss: 1.2011
Epoch 13/150
4/4 - 0s - 7ms/step - accuracy: 0.4538 - loss: 1.1917
Epoch 14/150
4/4 - 0s - 14ms/step - accuracy: 0.5462 - loss: 1.1826
Epoch 15/150
4/4 - 0s - 7ms/step - accuracy: 0.6387 - loss: 1.17

In [114]:
preds = model.predict(x_test)
predicted_classes =np.argmax(preds, axis=1)
predicted_classes

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([1, 0, 2, 1, 2, 0, 1, 2, 1, 2, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [117]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
confusion_matrix(y_test, predicted_classes)

array([[10,  0,  0],
       [ 0,  7,  2],
       [ 0,  0, 11]])

In [116]:
accuracy_score(y_test, predicted_classes)

0.9333333333333333

In [119]:
f1_score(y_test, predicted_classes, average='weighted')

0.9319444444444444

In [120]:
model.save('irismodel.h5')

In [121]:
from keras.models import load_model
new_model = load_model('irismodel.h5')

In [122]:
new_model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[2.3676515e-02, 5.1159787e-01, 4.6472549e-01],
       [9.9022657e-01, 8.8176746e-03, 9.5575931e-04],
       [1.0137189e-03, 2.6991075e-01, 7.2907549e-01],
       [8.1875227e-02, 5.5537051e-01, 3.6275420e-01],
       [8.0434680e-03, 4.1980127e-01, 5.7215530e-01],
       [9.9576151e-01, 3.9139506e-03, 3.2451769e-04],
       [1.9785294e-02, 5.0698811e-01, 4.7322664e-01],
       [2.9408650e-03, 3.2420129e-01, 6.7285788e-01],
       [4.4642776e-02, 5.3540891e-01, 4.1994828e-01],
       [1.0937158e-02, 4.2928594e-01, 5.5977690e-01],
       [8.0851028e-03, 4.1733694e-01, 5.7457805e-01],
       [9.8813879e-01, 1.0389966e-02, 1.4711469e-03],
       [9.7629434e-01, 2.0568224e-02, 3.1374265e-03],
       [9.8468858e-01, 1.3725129e-02, 1.5861769e-03],
       [9.6633196e-01, 2.9491562e-02, 4.1763694e-03],
       [1.7498598e-01, 5.2338344e-01, 3.0163059e-01],
       [8.2706539e-03, 4.2512819e-01, 5.6660116e-01],
       [2.2377204e-02, 5.0201732e-01, 4.7560543e-01],
       [2.4859151e-02, 5.266